[package]
name = "simple-db"
version = "0.1.0"
authors = ["Tahmid Sadik <tahmidsadik112@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.2.1"
prettytable-rs = "^0.8"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.2.0"
sqlparser = "0.5.0"
